name: Tests
on: [push]
jobs:
  commit-lint:
    name: Lint commit
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1
  feature:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Run action
        uses: ./
        with:
          filename: ./tests/test.txt
        env:
          NAME: mate
          COLOUR: purple
      - name: Print output
        run: cat ./tests/test.txt
      - name: Test
        run: '[[ "$(cat ./tests/test.txt)" = "Hi mate. My favourite colour is purple." ]]'
